'use client';

import { useState } from 'react';
import { demiurgeRpc } from '@/lib/demiurge-rpc';
import { qorAuth } from '@demiurge/qor-sdk';
import {
  generateKeypairFromQorId,
  signTransactionPayload,
  initWasm,
} from '@/lib/wasm-wallet';
import { generateAddressFromQorId } from '@/lib/qor-wallet';

interface ValidatorRegistrationProps {
  onRegistered?: () => void;
}

export function ValidatorRegistration({ onRegistered }: ValidatorRegistrationProps) {
  const [step, setStep] = useState<'form' | 'confirm' | 'submitting' | 'success' | 'error'>('form');
  const [stake, setStake] = useState('');
  const [commission, setCommission] = useState('10');
  const [sessionKey, setSessionKey] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [txResult, setTxResult] = useState<string | null>(null);

  const handleSubmit = async () => {
    setError(null);

    // Validate inputs
    const stakeNum = parseFloat(stake);
    if (isNaN(stakeNum) || stakeNum < 100) {
      setError('Minimum stake is 100 CGT');
      return;
    }

    const commissionNum = parseFloat(commission);
    if (isNaN(commissionNum) || commissionNum < 0 || commissionNum > 100) {
      setError('Commission must be between 0% and 100%');
      return;
    }

    if (!sessionKey || sessionKey.length < 10) {
      setError('Please enter a valid session key (generated by your node)');
      return;
    }

    setStep('confirm');
  };

  const handleConfirm = async () => {
    setStep('submitting');
    setError(null);

    try {
      await initWasm();

      const user = await qorAuth.getProfile();
      if (!user) throw new Error('Not authenticated. Please log in.');

      const address = generateAddressFromQorId(user.qor_id);
      const keypairJson = await generateKeypairFromQorId(user.qor_id);

      // Convert CGT to smallest units
      const stakeUnits = Math.floor(parseFloat(stake) * 100).toString();
      const commissionNum = parseFloat(commission);

      // Sign the registration payload
      const payloadStr = JSON.stringify({
        action: 'register_validator',
        account: address,
        stake: stakeUnits,
        commission: commissionNum,
        sessionKey,
      });
      const payloadBytes = new TextEncoder().encode(payloadStr);
      const signature = await signTransactionPayload(keypairJson, payloadBytes);

      const result = await demiurgeRpc.registerValidator(
        address,
        stakeUnits,
        commissionNum,
        sessionKey,
        signature
      );

      if (result.success) {
        setTxResult(result.message);
        setStep('success');
        onRegistered?.();
      } else {
        throw new Error(result.message || 'Registration failed');
      }
    } catch (err: any) {
      setError(err.message || 'Failed to register as validator');
      setStep('error');
    }
  };

  if (step === 'success') {
    return (
      <div className="glass-panel rounded-lg p-6 border border-green-500/30">
        <div className="text-center">
          <div className="text-4xl mb-4">✅</div>
          <h3 className="text-xl font-bold text-green-400 mb-2">Validator Registered</h3>
          <p className="text-gray-400 text-sm mb-4">
            {txResult || 'Your validator has been registered successfully.'}
          </p>
          <p className="text-xs text-gray-500">
            Ensure your node is running with the session key to start validating blocks.
          </p>
          <button
            onClick={() => setStep('form')}
            className="mt-4 px-6 py-2 bg-gray-800 text-white rounded-lg hover:bg-gray-700 transition-colors text-sm"
          >
            Done
          </button>
        </div>
      </div>
    );
  }

  if (step === 'submitting') {
    return (
      <div className="glass-panel rounded-lg p-6 border border-gray-700">
        <div className="text-center py-8">
          <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-demiurge-cyan mx-auto mb-4" />
          <p className="text-gray-400">Submitting validator registration...</p>
          <p className="text-xs text-gray-500 mt-2">Signing and broadcasting transaction</p>
        </div>
      </div>
    );
  }

  if (step === 'confirm') {
    return (
      <div className="glass-panel rounded-lg p-6 border border-yellow-500/30">
        <h3 className="text-xl font-bold text-white mb-4">Confirm Registration</h3>
        <div className="space-y-3 mb-6">
          <div className="flex justify-between text-sm">
            <span className="text-gray-400">Stake Amount</span>
            <span className="text-white font-bold">{stake} CGT</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-gray-400">Commission</span>
            <span className="text-white font-bold">{commission}%</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-gray-400">Session Key</span>
            <span className="text-white font-mono text-xs">{sessionKey.slice(0, 16)}...{sessionKey.slice(-8)}</span>
          </div>
        </div>
        <div className="bg-yellow-900/30 border border-yellow-500/30 rounded-lg p-3 mb-6">
          <p className="text-yellow-300 text-xs">
            Your staked CGT will be locked while you are an active validator.
            Unstaking requires a cooldown period.
          </p>
        </div>
        {error && (
          <div className="bg-red-900/30 border border-red-500/50 rounded p-3 text-red-400 text-sm mb-4">
            {error}
          </div>
        )}
        <div className="flex gap-3">
          <button
            onClick={() => setStep('form')}
            className="flex-1 py-2 bg-gray-800 text-white rounded-lg hover:bg-gray-700 transition-colors text-sm"
          >
            Back
          </button>
          <button
            onClick={handleConfirm}
            className="flex-1 py-2 bg-gradient-to-r from-demiurge-cyan to-green-500 text-black font-bold rounded-lg hover:opacity-90 transition-opacity text-sm"
          >
            Register Validator
          </button>
        </div>
      </div>
    );
  }

  // Form or error state
  return (
    <div className="glass-panel rounded-lg p-6 border border-gray-700">
      <h3 className="text-xl font-bold text-white mb-2">Register as Validator</h3>
      <p className="text-sm text-gray-400 mb-6">
        Run a validator node to secure the network and earn block rewards.
      </p>

      <div className="space-y-4">
        {/* Stake Amount */}
        <div>
          <label className="block text-sm text-gray-400 mb-1">Stake Amount (CGT)</label>
          <input
            type="number"
            min="100"
            step="1"
            value={stake}
            onChange={(e) => setStake(e.target.value)}
            placeholder="Minimum 100 CGT"
            className="w-full bg-gray-800/50 border border-gray-700 rounded-lg p-3 text-white placeholder-gray-500 focus:border-demiurge-cyan focus:outline-none"
          />
          <p className="text-xs text-gray-500 mt-1">Minimum stake: 100 CGT. Higher stake = higher chance of block production.</p>
        </div>

        {/* Commission */}
        <div>
          <label className="block text-sm text-gray-400 mb-1">Commission Rate (%)</label>
          <div className="flex items-center gap-3">
            <input
              type="range"
              min="0"
              max="100"
              step="1"
              value={commission}
              onChange={(e) => setCommission(e.target.value)}
              className="flex-1 accent-demiurge-cyan"
            />
            <div className="w-16 bg-gray-800/50 border border-gray-700 rounded px-2 py-1 text-center text-white text-sm font-mono">
              {commission}%
            </div>
          </div>
          <p className="text-xs text-gray-500 mt-1">Percentage of nominator rewards you keep. Lower commission attracts more nominators.</p>
        </div>

        {/* Session Key */}
        <div>
          <label className="block text-sm text-gray-400 mb-1">Session Key</label>
          <input
            type="text"
            value={sessionKey}
            onChange={(e) => setSessionKey(e.target.value)}
            placeholder="0x..."
            className="w-full bg-gray-800/50 border border-gray-700 rounded-lg p-3 text-white font-mono text-sm placeholder-gray-500 focus:border-demiurge-cyan focus:outline-none"
          />
          <p className="text-xs text-gray-500 mt-1">
            Generated by your node with <code className="text-demiurge-cyan">--generate-session-key</code>. Required to produce blocks.
          </p>
        </div>

        {(error || step === 'error') && (
          <div className="bg-red-900/30 border border-red-500/50 rounded p-3 text-red-400 text-sm">
            {error}
          </div>
        )}

        {/* Requirements */}
        <div className="bg-gray-800/30 border border-gray-700 rounded-lg p-4">
          <h4 className="text-sm font-semibold text-white mb-2">Requirements</h4>
          <ul className="space-y-1 text-xs text-gray-400">
            <li className="flex items-center gap-2">
              <span className="text-demiurge-cyan">•</span>
              Running Demiurge node with <code className="text-demiurge-cyan">--validator</code> flag
            </li>
            <li className="flex items-center gap-2">
              <span className="text-demiurge-cyan">•</span>
              Minimum 100 CGT staked
            </li>
            <li className="flex items-center gap-2">
              <span className="text-demiurge-cyan">•</span>
              Stable internet connection (99.9% uptime recommended)
            </li>
            <li className="flex items-center gap-2">
              <span className="text-demiurge-cyan">•</span>
              Valid session key from your node
            </li>
          </ul>
        </div>

        <button
          onClick={handleSubmit}
          disabled={!stake || !sessionKey}
          className="w-full py-3 bg-gradient-to-r from-demiurge-cyan to-green-500 text-black font-bold rounded-lg hover:opacity-90 transition-opacity disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Continue to Review
        </button>
      </div>
    </div>
  );
}
